#! /bin/sh
apt-get -y install avahi-daemon avahi-autoipd libnss-mdns avahi-utils libconfig-dev
ln -s /usr/local/bin/shairport-sync /usr/bin/shairport-sync
getent group shairport-sync &>/dev/null || sudo groupadd -r shairport-sync >/dev/null
getent passwd shairport-sync &> /dev/null || sudo useradd -r -M -g shairport-sync -s /usr/bin/nologin -G audio shairport-sync >/dev/null
sudo chmod 777 /usr/local/bin/shairport-sync
sudo chmod 777 /etc/shairport-sync.conf
rm -f /usr/lib/systemd/system/shairport-sync.service
#sudo systemctl enable shairport-sync
#sudo update-rc.d shairport-sync defaults 90 10
#service shairport-sync start
reboot
