#! /bin/sh
cat /proc/asound/* | grep USB
cat /proc/asound/* | grep speed
cat /proc/asound/card1/* | grep Status
cat /proc/asound/card1/pcm0p/* | grep id
cat /proc/asound/card1/pcm0p/* | grep name
cat /proc/asound/card1/pcm0p/sub0/* | grep access
cat /proc/asound/card1/pcm0p/sub0/* | grep format 
cat /proc/asound/card1/pcm0p/sub0/* | grep state
cat /proc/asound/card1/pcm0p/sub0/* | grep channels
cat /proc/asound/card1/pcm0p/sub0/* | grep rate
cat /proc/asound/card0/* | grep Status
cat /proc/asound/card0/pcm0p/* | grep id
cat /proc/asound/card0/pcm0p/* | grep name
cat /proc/asound/card0/pcm0p/sub0/* | grep access
cat /proc/asound/card0/pcm0p/sub0/* | grep format 
cat /proc/asound/card0/pcm0p/sub0/* | grep state
cat /proc/asound/card0/pcm0p/sub0/* | grep channels
cat /proc/asound/card0/pcm0p/sub0/* | grep rate
cat /proc/asound/card2/* | grep Status
cat /proc/asound/card2/pcm0p/* | grep id
cat /proc/asound/card2/pcm0p/* | grep name
cat /proc/asound/card2/pcm0p/sub0/* | grep access
cat /proc/asound/card2/pcm0p/sub0/* | grep format 
cat /proc/asound/card2/pcm0p/sub0/* | grep state
cat /proc/asound/card2/pcm0p/sub0/* | grep channels
cat /proc/asound/card2/pcm0p/sub0/* | grep rate 
cat /proc/asound/card3/* | grep Status
cat /proc/asound/card3/pcm0p/* | grep id
cat /proc/asound/card3/pcm0p/* | grep name
cat /proc/asound/card3/pcm0p/sub0/* | grep access
cat /proc/asound/card3/pcm0p/sub0/* | grep format 
cat /proc/asound/card3/pcm0p/sub0/* | grep state
cat /proc/asound/card3/pcm0p/sub0/* | grep channels
cat /proc/asound/card3/pcm0p/sub0/* | grep rate
echo "
Dsd Over Pcm" && cat /etc/mpd.conf | grep dop 

echo "
DSD Native Mode" && cat /etc/mpd.conf | grep dsd_native

echo "  
                        
USB DEVICES" 
lsusb