#! /bin/sh
sudo umount -f /mnt/NAS/*
sudo umount -l /mnt/NAS/*
sudo rm -r /mnt/NAS/*
sudo rm -r /mnt/NAS*
sudo rm -r /var/lib/mpd/music/NAS*
mv /var/www/db/player.db /var/www/db/bkp.db
cp /var/www/db/bkp.db /var/www/db/player.db
chmod 777 /var/www/db/player.db
sqlite3 /var/www/db/player.db 'delete from cfg_source'
sudo mkdir /mnt/NAS
cd /var/lib/mpd/music/
sudo ln -s /mnt/NAS /var/lib/mpd/music/NAS
echo "External Network Drive Deleted. PLEASE UPDATE LYBRARY!!!!!"
