#! /bin/sh
sudo service mpd stop
sudo umount -l /mnt/NAS/*
sudo rm -r /mnt/NAS/*
mv /var/www/db/player.db /var/www/db/bkp.db
cp /var/www/db/bkp.db /var/www/db/player.db
chmod 777 /var/www/db/player.db
sqlite3 /var/www/db/player.db 'delete from cfg_source'
sudo service mpd restart
sudo mkdir /mnt/NAS
sudo ln -s /mnt/NAS /var/lib/mpd/music/NAS
