#!/bin/bash
for file in /var/log/lastlog /var/log/syslog /var/log/kern.log /var/log/dmesg /var/log/dpkg.log /var/log/php5-fpm.log /var/log/php_errors.log /var/log/messages /var/log/daemon.log /var/log/utmp /var/log/wtmp /var/log/mpd/mpd.log /var/log/nginx/access.log /var/log/nginx/error.log /var/log/nginx/db.log /var/log/nginx/command.log /var/log/mpd/mpd.log /var/log/samba/log.smbd /var/log/samba/log.nmbd /var/log/auth.log ; do
unlink $file
ln -s /dev/null $file
done
