#! /bin/sh
sudo mpc stop
sudo mpd stop
sudo umount -f /mnt/USB
sudo umount -l /mnt/USB
sudo fsck -y /dev/sda1
sudo mount /dev/sda1 /mnt/USB
sudo mpd start
sudo mpc start
echo Passed! If the above errors does not, then all OK!!!
