#! /bin/sh
print "Content-Type: text/html\n\n";
sudo mpc stop
service mpd stop
sudo umount -f /mnt/USB
sudo umount -l /mnt/USB
sudo umount -l /dev/sda1
hdparm -i /dev/sda
sudo fsck -y /dev/sda1
sudo tune2fs -m 0 /dev/sda1
sudo mount /dev/sda1 /mnt/USB
sudo mpd start
sudo mpc start
service mpd start
echo Passed! If the above errors does not, then all OK!!!
