#! /bin/sh
mkdir /mnt/USB/sda1
mkdir /mnt/USB/sda2
mkdir /mnt/USB/sdb1
mkdir /mnt/USB/sdb2
chmod -R 777 /mnt/USB/*
mount /dev/sda1 /mnt/USB/sda1
mount /dev/sda1 /mnt/USB/sda2
mount /dev/sdb1 /mnt/USB/sdb1
mount /dev/sdb2 /mnt/USB/sdb2
chmod -R 777 /mnt/USB/*
exit 0
