#!/bin/bash
wget -q -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
echo -e "deb http://apt.mopidy.com/ stable main contrib non-free\ndeb-src http://apt.mopidy.com/ stable main contrib non-free" | sudo tee /etc/apt/sources.list.d/mopidy.list
sudo apt-get update
apt-get -y install cmake telnet libjson-glib-dev libao-dev libdbus-glib-1-dev libnotify-dev libsoup2.4-dev libsox-dev libspotify-dev
mkdir -p /home/osmc/gitrepos
cd /home/osmc/gitrepos
git clone git://github.com/Schnouki/spop.git
# Copy the configuration into a new config
echo "Preparing to compile and build..."
mkdir -p ~/.config/spop
# The default config file contains too many variables, causing volumio to be unable to set it up
cp spop/spopd.conf.sample /etc/spopd.conf
# Try to build spop
cd /home/osmc/gitrepos/spop
cmake -DCMAKE_INSTALL_PREFIX=/usr
make
make install
chmod 777 /etc/spopd.conf
git clone https://github.com/norrest/volumio.git /update/tmpi/
sudo chmod -R 777 /update/tmpi
sudo cp -pfR /update/tmpi/spoty/ /www/
service nginx restart && service php5-fpm restart
exit 0
