#! /bin/sh
# /etc/init.d/shairport-sync
#
### BEGIN INIT INFO
# Provides:          shairport-sync
# Required-Start:    alsa-utils hostname avahi
# Required-Stop:     alsa-utils hostname avahi
# Short-Description: shairport-sync - Airtunes emulator!
# Description:       Airtunes emulator!
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO
NAME="VAMP"

case "$1" in
  start)
    /usr/local/bin/shairport-sync -d -a "$NAME" -w -B "mpc stop"
    ;;
  stop)
    killall shairport-sync
    ;;
  *)
    echo "Usage: /etc/init.d/shairport-sync {start|stop}"
    exit 1
    ;;
esac

exit 0
