#! /bin/sh
sudo chmod -R 777 /var/lib/mpd/playlists/
sudo apt-get -y update && sudo apt-get install -y git-core
sudo git clone https://github.com/norrest/volumio.git /update/tmpi
sudo apt-get -y remove git-core
sudo chmod -R 777 /update/tmpi
cp -arpf /update/tmpi/etc/ /
cp -arpf /update/tmpi/var/ /
cp -arpf /update/tmpi/update/ /update
sudo rm -R /update/tmpi
echo "$(tput setaf 1)[+] All done! please reboot )"